name: WisdomAtWork
favicon: null
layout_spectrum: 0.2335324918385595
typography_spectrum: 0.5306858788244426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3224554790649563
  lightness: 0.8966143534053117
  saturation: 0.9029232754837722
  rhythmicContrast: 0.6837746729142964
purpose: []
